### ISSUE TITLE
[feat] Linux Support

### ISSUE THREAD

**Issue by AuroraTea** [ayangweb/EcoPaste#75]
- [x] 窗口正常聚焦 by @AuroraTea in #143
- [x] 导入和导出 by @ayangweb in #110
- [x] 实现 `preview_path` 方法 by @zpp0196 in #214
- [x] 开机自动启动时不显示窗口 by @ayangweb in #211
- [x] 自动粘贴功能 by @zpp0196 in #317
- [x] OCR 图片识别 by @zpp0196 in #334

**Comment by ayangweb** [comment]
@AuroraTea #79 切换主题卡顿的 bug 已修复！

**Comment by ayangweb** [comment]
@AuroraTea #84 现已提供同步的 `isLinux` 方法使用

**Comment by ayangweb** [comment]
#85 linux 键盘样式已适配平台常见风格

**Comment by TimelessDreamer** [comment]
适配 linux 的双击托盘图标，打开应用！

**Comment by ayangweb** [comment]
> 适配 linux 的双击托盘图标，打开应用！

#91 windows 新增了单击托盘配置项，此配置项同样适用于 linux（改名双击托盘），等完全支持 linux 时，可开放此配置项！

**Comment by ayangweb** [comment]
@AuroraTea #110 现已支持导入和导出数据，空了在 linux 上测试！

**Comment by ayangweb** [comment]
windows 和 macos 已实现回填效果，linux 需要实现 `focus_previous_window` 方法来聚焦上一个窗口完成回填！

**Comment by ayangweb** [comment]
@AuroraTea #211 支持了开机自启动时不显示窗口，linux 需要单独测试下！

**Comment by zpp0196** [comment]
> #85 linux 快捷键设置样式已适配平台常见风格

* i3wm/sway 环境快捷键无法生效，临时解决方案

```
bindsym $mod+c exec "/path/to/eco-paste"
```

* wayland 不支持注册全局快捷键 https://github.com/tauri-apps/tauri/issues/3578

> @AuroraTea #110 现已支持导入和导出数据，空了在 linux 上测试！

* [preview_path](https://github.com/ayangweb/EcoPaste/blob/b4fdd3465c50a1a060c38c98a81009cc6fecd561/src-tauri/src/plugins/fs_extra.rs#L70) 未适配 linux，可以考虑使用 [xdg-open](https://linux.die.net/man/1/xdg-open) 或 [showfile](https://github.com/jf2048/showfile)

> @AuroraTea windows 和 macos 已实现回填效果，linux 需要实现 `focus_previous_window` 方法来聚焦上一个窗口完成回填！

* i3wm/sway 环境(`focus_previous_window` 空实现)大部分情况下可以正常回填，alacritty 等应用可能需要 `Ctrl+Shift+V` 才能粘贴，是否可以考虑换成类似 [enigo](https://github.com/enigo-rs/enigo) 的模拟输入方案
* 其它桌面环境未测试，待后续测试补充

> @AuroraTea #211 支持了开机自启动时不显示窗口，linux 需要单独测试下！

`~/.config/autostart/EcoPaste.desktop` 文件内容如下

```desktop
[Desktop Entry]
Type=Application
Version=1.0
Name=EcoPaste
Comment=EcoPastestartup script
Exec=/path/to/eco-paste --auto-launch
StartupNotify=false
Terminal=false
```

* `--auto-launch` 参数测试 OK
* `~/.config/autostart` 并不适用所有 linux 环境

**Comment by ayangweb** [comment]
@zpp0196 感谢大佬反馈！

关于 [preview_path](https://github.com/ayangweb/EcoPaste/blob/b4fdd3465c50a1a060c38c98a81009cc6fecd561/src-tauri/src/plugins/fs_extra.rs#L70) 的实现是否可以提供一个 pr 呢？

**Comment by zpp0196** [comment]
如果启动白屏可以尝试添加以下环境变量解决

```bash
WEBKIT_DISABLE_COMPOSITING_MODE=1
```

上游问题：https://github.com/tauri-apps/tauri/issues/5143#issuecomment-1311815517

**Comment by zpp0196** [comment]
wayland 快捷键问题移动到 #335 讨论
